# Generated by Django 4.2 on 2023-04-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(default=3)),
                ('delivery', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
