# Generated by Django 4.2 on 2023-04-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='delivery',
            field=models.CharField(max_length=30),
        ),
    ]
