# Generated by Django 4.2 on 2023-04-30 20:11

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='avatar',
            field=models.ImageField(default=home.models.Category, upload_to='avatars'),
        ),
    ]
