# Generated by Django 4.2 on 2023-04-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_category_options_product_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avatar',
        ),
    ]
