# Generated by Django 4.2 on 2023-05-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_order_user_shopping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='product',
            new_name='order',
        ),
    ]
