# Generated by Django 4.2 on 2023-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_order_product_remove_shopping_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
