# Generated by Django 4.2 on 2023-05-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_product_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'id'},
        ),
    ]
